# Documentation for VacationRentals WordPress theme.
#
# Author: Ahmad Awais
# License: Copyright held by WPTie.
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/
site_name: VR DOCUMENTATION
site_description: 'Documentation for Vacation Rentals WordPress theme.'
site_author: 'Ahmad Awais'
site_url: 'https://ahmadawais.github.io/vrdoc'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ahmadawais/vrdoc'

# Copyright
copyright: 'Copyright &copy; 2017 WPCouple (Ahmad Awais & Maedah Batool)'


theme: 'material'
theme_dir: 'mkdocs-material/material'

pages:
    # - —— PROGRESS: progress.md
    - 0. START HERE: index.md
    - 1. INSTALLATION: installation.md
    - 2. CUSTOMIZATION: customization.md
    - 3. PAGES:
        - HOMEPAGE: homepage.md
        - RENTALS SEARCH: rentals-search.md
        - RENTALS LIST: rentals-list.md
        - LOGIN: login.md
        - REGISTER: register.md
        - RESET: reset.md
        - EDIT PROFIE: edit-profile.md
        - FAVORITE: favorite.md
    - 4. RENTALS: rentals.md
    - 5. DESTINATIONS: destinations.md
    - 6. FEATURES: features.md
    - 7. TYPES: types.md
    - 8. BOOKINGS: bookings.md
    - 9. AGENTS: agents.md
    - 10. SETTINGS: settings.md
    # - Eg: eg.md

extra:
  palette:
    primary: 'indego'
    accent: 'deep orange'
  font:
      text: 'Open Sans'
      code: 'Ubuntu Mono'
  # logo: 'images/logo.svg'
  # social:
  #     - type: 'github'
  #       link: 'https://github.com/ahmadawais/'
  #     - type: 'twitter'
  #       link: 'https://twitter.com/MrAhmadAwais'

# # Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta
